export const CHANGE_CATEGORY="CHANGE_CATEGORY"
export const GET_CATEGORIES_SUCCESS="GET_CATEGORIES_SUCCESS"

export const GET_BLOGPOSTS_SUCCESS="GET_BLOGPOSTS_SUCCESS"

export const CREATE_BLOGPOST_SUCCESS="CREATE_BLOGPOST_SUCCESS"
export const UPDATE_BLOGPOST_SUCCESS="UPDATE_BLOGPOST_SUCCESS"



